name: Build apk and upload artifact

on:
  push:
    branches: [ main ]
  pull_request:
    types: "*"
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: britannio/action-install-flutter@v1.1

      - name: Install deps & try apk build
        run: | 
          flutter pub get
          flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          path: build/app/outputs/flutter-apk/app-release.apk
